name = "DevAirBorne"
uuid = "8dfed614-7d1f-4dd8-a126-b47d2ae9e134"
authors = ["Bruno Castro Ibarburu"]
version = "1.0.0-DEV"

[deps]
AirBorne = "4a232ea9-7d1f-4dd8-a126-b47d2ae9e134"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
