name: SpellCheck

on: [pull_request, workflow_dispatch]

jobs:
  typos-check:
    name: Spell Check with Typos
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.8.5'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v3
      - name: Check spelling
        uses: crate-ci/typos@v1.14.12
        with: 
          config: .github/_typos.toml
          write_changes: false